### PR TITLE
Resolved issue with faraday gem namespace changes in v0.8x. Moved from t...

### PR DESCRIPTION
**Pull request by theboxfactory**
Modified windy to use the faraday_middleware gem and not the original faraday gem, as the namespaces have been restructured across different faraday gems from around version 0.8x

### CODE REVIEW

**Comment by srobbin** [comment]
Thank you!

**Comment by theboxfactory** [comment]
Thanks Scott,

Will this get pushed to the rubygems.org site at some point as well?

**Comment by srobbin** [comment]
Yes. Let me look into that today, and I'll get back to you.

**Comment by theboxfactory** [comment]
Thanks. I also didn't kick up the version number, so that should probably move to 1.1.2?

**Comment by srobbin** [comment]
Ah, yeah. I'll take care of that. Thanks.

**Comment by srobbin** [comment]
Sorry for the delay. The new version is now up on RubyGems.org.

**Comment by theboxfactory** [comment]
Not a problem. Thanks so much for your assistance and helping to provide these excellent libraries.

**Pull request merged**
